# Generated by Django 4.2.2 on 2023-08-03 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=225)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('Destination_id', models.IntegerField(default=None)),
                ('total_memebers', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('suv', 'SUV'), ('Hatchback', 'HATCHBACK'), ('minivan', 'MINIVAN'), ('jeep', 'JEEP')], max_length=50)),
                ('date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('residency1', models.CharField(choices=[('hotel', 'HOTEL'), ('vacation rentals', 'VECATION RENTALS'), ('resorts', 'RESORTS'), ('camping', 'CAMPING')], max_length=50)),
                ('residency2', models.CharField(choices=[('hotel', 'HOTEL'), ('vacation rentals', 'VECATION RENTALS'), ('resorts', 'RESORTS'), ('camping', 'CAMPING')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_id', models.IntegerField()),
                ('travel', models.TextField()),
                ('name', models.ForeignKey(max_length=225, on_delete=django.db.models.deletion.CASCADE, to='items.agencies')),
            ],
        ),
    ]
