# Generated by Django 4.2.2 on 2023-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='agency_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
